#include "main.h"
#include "passes.h"


extern char *pre_process(char *nameFile);

/**
 * Main function for the assembler program.
 *
 * @param argc The number of command-line arguments.
 * @param argv An array of strings representing the command-line arguments, where each argument is a file name.
 * @return Returns 0 upon successful completion.
 *
 * The main function processes each input file provided via command-line arguments.
 * It performs the following steps for each file:
 * 1. Pre-processes the file to handle macros and generate an intermediate file.
 * 2. Conducts the first pass to determine symbol addresses and collect information.
 * 3. Conducts the second pass to generate the final machine code and detect any remaining errors.
 * 4. Outputs the final object file (.ob), entry file (.ent), and external file (.ext) if applicable.
 *
 * Memory cleanup is performed after processing each file to ensure no memory leaks.
 */
int main(int argc, char *argv[]){
	int i, j;
	int flag_error;
	char * nameFile_am;
	FILE * file_am;
	struct translation_unit prog_code = {0};/*Initialize the translation unit structure*/
	for(i = 1; i < argc; i++){/*Iterate over each input file*/
		nameFile_am = pre_process(argv[i]);/* Pre-process the file to handle macros*/
		memset(&prog_code, 0 ,sizeof(struct translation_unit));/*Reset the translation unit for each file*/
		if(nameFile_am){/*If pre-processing is successful*/
			file_am = fopen(nameFile_am ,"r");/*Open the intermediate file generated by pre-processing*/
			if(file_am){
				flag_error = first_pass(&prog_code ,file_am ,nameFile_am);/*Perform the first pass*/
				if(!flag_error){/*If no errors in the first pass*/
					rewind(file_am);/*Rewind the file for the second pass*/
					flag_error = second_pass(&prog_code ,file_am ,nameFile_am);/*Perform the second pass*/
					if(!flag_error){
						print_file_ob(argv[i] , &prog_code);/* Output the object file (.ob)*/
						if(prog_code.count_ent > 0)print_file_ent(argv[i] , &prog_code);/*Output the entry file (.ent) if entries exist*/
						if(prog_code.count_ext > 0)print_file_ext(argv[i] , &prog_code);/*Output the external file (.ext) if externals exist*/
					}
				}
				fclose(file_am);
			}
			free(nameFile_am);
        }	
		/*Clean up the memory allocated for the translation unit's components*/
		free(prog_code.code_content);
		free(prog_code.data_content);
		free(prog_code.symbol_table);
		for (j = 0; j < prog_code.count_ext; j++) {
			free(prog_code.ext_table[j].addressesExt_sym);
		}
		free(prog_code.ext_table);
		free(prog_code.entries);
	}
	return 0;
}
